[client]
showErrorDetails = false
toolbarMode = "viewer"

[theme]
base = "dark"
primaryColor = "#FFD700"
backgroundColor = "#0F1116"
secondaryBackgroundColor = "#1E212B"
textColor = "#EAEAEA"
font = "sans serif"

[ui]
hideTopBar = true
